name: 'Docker Test'

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to DockerHub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Build and push docker image
        run: docker buildx build --platform=linux/amd64,linux/arm/v7,linux/arm64 --output "type=image,push=true" --file ./Dockerfile . --tag itachi1706/handbrake-multiarch:test
